import { ComponentMetadata } from './types';

export const componentsData: ComponentMetadata[] = [
  {
    id: 'button',
    name: 'Button',
    description: 'A versatile button component with multiple variants, sizes, and states including gradient effects and loading states.',
    category: 'Button',
    complexity: 'Basic',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['interactive', 'form', 'cta', 'gradient'],
    variants: ['primary', 'secondary', 'ghost', 'danger', 'success'],
    useCases: ['Form submission', 'Call-to-action', 'Navigation'],
    accessibility: {
      wcag: ['WCAG 2.1 AA compliant', 'Color contrast ratio > 4.5:1'],
      keyboardSupport: ['Enter/Space to activate', 'Tab navigation'],
      screenReader: ['Accessible name', 'State announcements'],
    },
  },
  {
    id: 'input',
    name: 'Text Input',
    description: 'A sleek input field with glassmorphic styling, focus states, and error handling.',
    category: 'Input',
    complexity: 'Basic',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['form', 'text', 'interactive', 'validation'],
    variants: ['default', 'error', 'disabled', 'with-icon'],
    useCases: ['Form fields', 'Search bars', 'User input'],
    accessibility: {
      wcag: ['WCAG 2.1 AA compliant', 'Proper labeling'],
      keyboardSupport: ['Tab navigation', 'Text input'],
      screenReader: ['Label association', 'Error announcements'],
    },
  },
  {
    id: 'card',
    name: 'Card',
    description: 'Glassmorphic card component with deep shadows and smooth hover effects.',
    category: 'Card',
    complexity: 'Basic',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['container', 'layout', 'glassmorphism'],
    variants: ['default', 'hover', 'interactive', 'with-image'],
    useCases: ['Content grouping', 'Product displays', 'Info panels'],
    accessibility: {
      wcag: ['Semantic HTML', 'Keyboard accessible if interactive'],
      keyboardSupport: ['Tab navigation for interactive cards'],
      screenReader: ['Proper heading hierarchy', 'Content structure'],
    },
  },
  {
    id: 'sphere-3d',
    name: '3D Sphere',
    description: 'CSS-only 3D sphere with gradient and lighting effects, featuring floating animation.',
    category: '3D Objects',
    complexity: 'Intermediate',
    frameworks: ['HTML/CSS', 'React'],
    tags: ['3d', 'decorative', 'gradient', 'animation'],
    variants: ['default', 'glowing', 'rotating'],
    useCases: ['Hero sections', 'Decorative elements', 'Brand identity'],
    accessibility: {
      wcag: ['Decorative - aria-hidden="true"'],
      keyboardSupport: ['Not interactive'],
      screenReader: ['Hidden from screen readers'],
    },
  },
  {
    id: 'badge',
    name: 'Badge',
    description: 'Small status or tag indicator with various color schemes and styles.',
    category: 'Data Display',
    complexity: 'Basic',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['label', 'tag', 'status', 'indicator'],
    variants: ['primary', 'success', 'warning', 'danger', 'info'],
    useCases: ['Status indicators', 'Tags', 'Labels', 'Counts'],
    accessibility: {
      wcag: ['Color contrast compliant', 'Not relying on color alone'],
      keyboardSupport: ['Not interactive unless clickable'],
      screenReader: ['Meaningful text content'],
    },
  },
  {
    id: 'modal',
    name: 'Modal',
    description: 'Glassmorphic modal dialog with smooth animations and focus management.',
    category: 'Modal',
    complexity: 'Intermediate',
    frameworks: ['React'],
    tags: ['overlay', 'dialog', 'popup', 'glassmorphism'],
    variants: ['default', 'small', 'large', 'fullscreen'],
    useCases: ['Confirmations', 'Forms', 'Details', 'Alerts'],
    accessibility: {
      wcag: ['Focus trap', 'ESC to close', 'ARIA dialog role'],
      keyboardSupport: ['Tab trapping', 'ESC key', 'Focus restoration'],
      screenReader: ['Dialog announcements', 'Accessible names'],
    },
  },
  {
    id: 'navigation',
    name: 'Navigation Menu',
    description: 'Responsive navigation with glassmorphic styling and smooth transitions.',
    category: 'Navigation',
    complexity: 'Intermediate',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['menu', 'nav', 'header', 'responsive'],
    variants: ['horizontal', 'vertical', 'sidebar', 'dropdown'],
    useCases: ['Site navigation', 'App menus', 'Mobile menus'],
    accessibility: {
      wcag: ['Keyboard navigation', 'ARIA navigation role'],
      keyboardSupport: ['Arrow keys', 'Tab navigation', 'Enter to activate'],
      screenReader: ['Navigation landmarks', 'Current page indication'],
    },
  },
  {
    id: 'data-chart',
    name: 'Data Chart',
    description: 'Beautiful gradient-filled charts for data visualization with purple-blue gradients.',
    category: 'Data Display',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['chart', 'graph', 'data', 'visualization', 'gradient'],
    variants: ['bar', 'line', 'donut', 'area'],
    useCases: ['Analytics dashboards', 'Reports', 'Statistics'],
    accessibility: {
      wcag: ['Text alternatives', 'Data tables for complex charts'],
      keyboardSupport: ['Navigable data points'],
      screenReader: ['Chart descriptions', 'Data summaries'],
    },
  },
  {
    id: 'loading-spinner',
    name: 'Loading Spinner',
    description: 'Animated loading indicators with gradient effects and smooth rotations.',
    category: 'Feedback',
    complexity: 'Basic',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['loading', 'spinner', 'feedback', 'animation'],
    variants: ['spinner', 'dots', 'bars', 'ring'],
    useCases: ['Loading states', 'Async operations', 'Page transitions'],
    accessibility: {
      wcag: ['ARIA live region', 'Loading announcements'],
      keyboardSupport: ['Not interactive'],
      screenReader: ['Loading status announcements'],
    },
  },
  {
    id: 'dropdown',
    name: 'Dropdown',
    description: 'Sleek dropdown menu with glassmorphic styling and smooth animations.',
    category: 'Form',
    complexity: 'Intermediate',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['select', 'menu', 'form', 'interactive'],
    variants: ['single-select', 'multi-select', 'searchable', 'grouped'],
    useCases: ['Form selections', 'Filter menus', 'Action menus'],
    accessibility: {
      wcag: ['Keyboard operable', 'ARIA combobox pattern'],
      keyboardSupport: ['Arrow keys', 'Type to search', 'Enter/Space'],
      screenReader: ['Selected option announcements', 'Options count'],
    },
  },
  {
    id: 'command-palette',
    name: 'Command Palette',
    description: 'Spotlight-style command palette with keyboard shortcuts, search, and grouped commands.',
    category: 'Navigation',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['search', 'navigation', 'keyboard', 'shortcuts'],
    variants: ['default', 'with-categories', 'with-icons'],
    useCases: ['Quick navigation', 'Command execution', 'Search functionality'],
    accessibility: {
      wcag: ['Keyboard first', 'Focus trap', 'ARIA dialog pattern'],
      keyboardSupport: ['Cmd/Ctrl+K to open', 'Arrow keys', 'Enter', 'ESC'],
      screenReader: ['Dialog announcements', 'Result count', 'Selection feedback'],
    },
  },
  {
    id: 'breadcrumbs',
    name: 'Breadcrumbs',
    description: 'Responsive breadcrumb navigation with truncation and ARIA support.',
    category: 'Navigation',
    complexity: 'Basic',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['navigation', 'hierarchy', 'wayfinding'],
    variants: ['default', 'collapsed', 'with-icons'],
    useCases: ['Page hierarchy', 'Navigation trail', 'Current location'],
    accessibility: {
      wcag: ['ARIA breadcrumb', 'Current page indication', 'Keyboard accessible'],
      keyboardSupport: ['Tab navigation', 'Enter to follow'],
      screenReader: ['Navigation landmark', 'Current page announcement'],
    },
  },
  {
    id: 'segmented-control',
    name: 'Segmented Control',
    description: 'Tabs-like control with visual selection ring and smooth animations.',
    category: 'Navigation',
    complexity: 'Intermediate',
    frameworks: ['React'],
    tags: ['tabs', 'switcher', 'selector', 'navigation'],
    variants: ['horizontal', 'vertical', 'with-icons'],
    useCases: ['View switcher', 'Tab navigation', 'Filter selection'],
    accessibility: {
      wcag: ['ARIA tabs pattern', 'Keyboard accessible', 'Focus visible'],
      keyboardSupport: ['Arrow keys', 'Home/End', 'Tab'],
      screenReader: ['Tab announcements', 'Selection state', 'Panel association'],
    },
  },
  {
    id: 'combobox',
    name: 'Combobox',
    description: 'Async searchable select with typeahead and keyboard navigation.',
    category: 'Form',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['autocomplete', 'search', 'select', 'typeahead'],
    variants: ['single-select', 'multi-select', 'async', 'creatable'],
    useCases: ['User search', 'Tag selection', 'Location picker', 'Category filter'],
    accessibility: {
      wcag: ['ARIA combobox pattern', 'Keyboard operable', 'Clear labeling'],
      keyboardSupport: ['Type to filter', 'Arrow keys', 'Enter', 'ESC'],
      screenReader: ['Result count', 'Selected items', 'Loading state'],
    },
  },
  {
    id: 'date-range',
    name: 'Date Range Picker',
    description: 'Keyboard-navigable dual calendar for selecting date ranges.',
    category: 'Form',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['date', 'calendar', 'range', 'picker'],
    variants: ['single-month', 'dual-month', 'with-presets'],
    useCases: ['Report filtering', 'Booking dates', 'Event scheduling'],
    accessibility: {
      wcag: ['Keyboard navigation', 'Date format announcements', 'ARIA grid'],
      keyboardSupport: ['Arrow keys', 'Page Up/Down', 'Home/End', 'Enter'],
      screenReader: ['Selected dates', 'Current month', 'Day announcements'],
    },
  },
  {
    id: 'file-uploader',
    name: 'File Uploader',
    description: 'Drag-and-drop file uploader with image crop and preview.',
    category: 'Form',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['upload', 'file', 'drag-drop', 'image'],
    variants: ['single-file', 'multi-file', 'with-crop', 'with-preview'],
    useCases: ['Profile picture', 'Document upload', 'Media library', 'Attachments'],
    accessibility: {
      wcag: ['Keyboard accessible', 'File input alternative', 'Progress feedback'],
      keyboardSupport: ['Tab to activate', 'Enter to browse'],
      screenReader: ['Upload instructions', 'File count', 'Upload progress'],
    },
  },
  {
    id: 'data-table',
    name: 'Data Table',
    description: 'Advanced table with pin, resize, sort, filter, and virtualization.',
    category: 'Data Display',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['table', 'grid', 'data', 'sortable', 'filterable'],
    variants: ['basic', 'sortable', 'filterable', 'editable', 'virtual'],
    useCases: ['Data grids', 'Admin panels', 'Reports', 'Spreadsheet-like'],
    accessibility: {
      wcag: ['Table headers', 'Sort announcements', 'Row/column headers'],
      keyboardSupport: ['Arrow keys', 'Page Up/Down', 'Home/End', 'Enter to edit'],
      screenReader: ['Table structure', 'Column headers', 'Sort direction', 'Row count'],
    },
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Chronological event timeline with badges and connectors.',
    category: 'Data Display',
    complexity: 'Intermediate',
    frameworks: ['React', 'HTML/CSS'],
    tags: ['timeline', 'history', 'events', 'chronological'],
    variants: ['vertical', 'horizontal', 'with-icons'],
    useCases: ['Activity feed', 'Process steps', 'History', 'Changelog'],
    accessibility: {
      wcag: ['Semantic ordering', 'Clear timestamps', 'Keyboard navigation'],
      keyboardSupport: ['Tab navigation', 'Focusable events'],
      screenReader: ['Chronological order', 'Event details', 'Timestamps'],
    },
  },
  {
    id: 'tree-view',
    name: 'Tree View',
    description: 'Nested list with expand/collapse and keyboard navigation.',
    category: 'Data Display',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['tree', 'hierarchy', 'nested', 'expandable'],
    variants: ['default', 'with-checkboxes', 'with-icons', 'draggable'],
    useCases: ['File browser', 'Organization chart', 'Category tree', 'Sitemap'],
    accessibility: {
      wcag: ['ARIA tree pattern', 'Keyboard navigation', 'Expand/collapse'],
      keyboardSupport: ['Arrow keys', 'Enter', 'Space', 'Home/End'],
      screenReader: ['Tree structure', 'Expanded/collapsed state', 'Level'],
    },
  },
  {
    id: 'drawer',
    name: 'Drawer / Sheet',
    description: 'Edge-anchored panel with focus trapping and scroll lock.',
    category: 'Overlay',
    complexity: 'Intermediate',
    frameworks: ['React'],
    tags: ['drawer', 'sheet', 'panel', 'overlay'],
    variants: ['left', 'right', 'top', 'bottom'],
    useCases: ['Side navigation', 'Filters', 'Details panel', 'Shopping cart'],
    accessibility: {
      wcag: ['Focus trap', 'ESC to close', 'ARIA dialog'],
      keyboardSupport: ['Tab trapping', 'ESC key', 'Focus restoration'],
      screenReader: ['Dialog announcements', 'Close button'],
    },
  },
  {
    id: 'popover',
    name: 'Popover / Menu',
    description: 'Floating panel with smart alignment and collision detection.',
    category: 'Overlay',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['popover', 'menu', 'dropdown', 'tooltip'],
    variants: ['menu', 'tooltip', 'dialog', 'context-menu'],
    useCases: ['Action menus', 'Context menus', 'Tooltips', 'Help text'],
    accessibility: {
      wcag: ['ARIA menu pattern', 'Keyboard navigation', 'Focus management'],
      keyboardSupport: ['Arrow keys', 'Enter', 'ESC', 'Tab'],
      screenReader: ['Menu announcements', 'Item count', 'Current item'],
    },
  },
  {
    id: 'toast-center',
    name: 'Toast Center',
    description: 'Stacked notification system with queue management and auto-dismiss.',
    category: 'Overlay',
    complexity: 'Intermediate',
    frameworks: ['React'],
    tags: ['toast', 'notification', 'alert', 'feedback'],
    variants: ['success', 'error', 'warning', 'info'],
    useCases: ['Success messages', 'Error notifications', 'Warnings', 'Info alerts'],
    accessibility: {
      wcag: ['ARIA live regions', 'Status role', 'Sufficient time to read'],
      keyboardSupport: ['Focusable dismiss', 'ESC to close'],
      screenReader: ['Polite announcements', 'Status updates'],
    },
  },
  {
    id: 'code-block',
    name: 'Code Block',
    description: 'Syntax-highlighted code display with copy button and line numbers.',
    category: 'Rich Content',
    complexity: 'Intermediate',
    frameworks: ['React'],
    tags: ['code', 'syntax', 'highlighting', 'copy'],
    variants: ['default', 'with-line-numbers', 'with-filename', 'with-diff'],
    useCases: ['Documentation', 'Code examples', 'Snippets', 'Tutorials'],
    accessibility: {
      wcag: ['Code announcements', 'Copy feedback', 'Keyboard accessible'],
      keyboardSupport: ['Tab to copy button', 'Ctrl+C to copy'],
      screenReader: ['Code language', 'Line count', 'Copy status'],
    },
  },
  {
    id: 'diff-viewer',
    name: 'Diff Viewer',
    description: 'Side-by-side or unified diff viewer for code comparison.',
    category: 'Rich Content',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['diff', 'comparison', 'code', 'changes'],
    variants: ['side-by-side', 'unified', 'split'],
    useCases: ['Code review', 'Version comparison', 'Change tracking'],
    accessibility: {
      wcag: ['Color and icon indicators', 'Change announcements', 'Navigation'],
      keyboardSupport: ['Arrow keys', 'Tab navigation', 'Jump to changes'],
      screenReader: ['Addition/deletion announcements', 'Line numbers', 'Change type'],
    },
  },
  {
    id: 'rich-text-editor',
    name: 'Rich Text Editor',
    description: 'Markdown-based WYSIWYG editor with formatting toolbar.',
    category: 'Rich Content',
    complexity: 'Advanced',
    frameworks: ['React'],
    tags: ['editor', 'wysiwyg', 'markdown', 'rich-text'],
    variants: ['basic', 'with-toolbar', 'split-view', 'full-featured'],
    useCases: ['Blog posts', 'Comments', 'Documentation', 'Content creation'],
    accessibility: {
      wcag: ['Keyboard shortcuts', 'Toolbar labels', 'Focus management'],
      keyboardSupport: ['Ctrl+B bold', 'Ctrl+I italic', 'Tab for toolbar'],
      screenReader: ['Formatting announcements', 'Character count', 'Current style'],
    },
  },
];

export const getComponentById = (id: string): ComponentMetadata | undefined => {
  return componentsData.find((c) => c.id === id);
};

export const getComponentsByCategory = (category: string): ComponentMetadata[] => {
  return componentsData.filter((c) => c.category === category);
};

export const getComponentsByComplexity = (complexity: string): ComponentMetadata[] => {
  return componentsData.filter((c) => c.complexity === complexity);
};

export const searchComponents = (query: string): ComponentMetadata[] => {
  const lowerQuery = query.toLowerCase();
  return componentsData.filter(
    (c) =>
      c.name.toLowerCase().includes(lowerQuery) ||
      c.description.toLowerCase().includes(lowerQuery) ||
      c.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
};
